name: abushakir
description: A Dart Package for Ethiopian Calendar system (ባሕረ ሃሳብ).
  This package can hep you integrate Ethiopian calendar system into your
  dart or flutter application. It also includes, Ethiopian Date and Time
  reckoning system and help you to get all the movable fastings with respective holidays.

version: 0.1.0
homepage: https://github.com/Nabute/Abushakir
documentation: https://github.com/Nabute/Abushakir/docs


environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  equatable: ^1.1.0

dev_dependencies:
  test: ^1.14.2